djangogirls/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from yonetim.views import index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^yonetim/', include('yonetim.urls', namespace='yonetim')),
    url(r'^$', view=index),
    url(r'^users/', include('users.urls', namespace='users')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


users/urls.py
from django.conf.urls import url
from .views import user_create, user_login, user_logout, user_edit_profile, user_list, user_delete, user_change_password, user_profile, user_upload_photo

urlpatterns = [
    url(r'^user_create/$', view=user_create, name='user_create'),
    url(r'^user_login/$', view=user_login, name='user_login'),
    url(r'^user_logout/$', view=user_logout, name='user_logout'),
    url(r'^user_upload_photo/$', user_upload_photo, name='user_upload_photo'),
    url(r'^user_edit_profile/$', view=user_edit_profile, name='user_edit_profile'),
    url(r'^user_list/$', view=user_list, name='user_list'),
    url(r'^delete/(?P<username>[-\w]+)/$', view=user_delete, name='user_delete'),
    url(r'^password_change/$', view=user_change_password, name='password_change'),
    url(r'^(?P<username>.+)/$', user_profile, name='user_profile')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block kodblok %}

    {% endblock %}

    <title>{% block title %} Görev Yönetimi {% endblock %}</title>


</head>
<body>
<nav class="navbar navbar-inverse" style="background-color: #363C69">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'yonetim:task_list' %}" style="color: #d0e9c6"><img style="height: 25px; width: 25px; margin-left: 10px" src="{{ '/static/img/logo-only.png' }}"/></a>
        {% else %}
            <a class="navbar-brand" style="color: #d0e9c6"><b>ROM</b></a>
        {% endif %}
    </div>

    <!-- Collect the nav links, forms, and other content for toggling anasayfanın classı active di-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="addlink"><a href="{% url 'yonetim:task_list' %}">Anasayfa <span class="sr-only">(current)</span></a></li>
            {% if request.user.is_superuser %}
                <li><a href="{% url 'yonetim:task_create' %}">Görev Oluştur</a></li>
                <li><a href="{% url 'users:user_create' %}">Çalışan Ekle</a></li>
                <li><a href="{% url 'users:user_list' %}">Kullanıcılar</a></li>
            {% endif %}
          {% endif %}
      </ul>
    {% if request.user.is_authenticated %}
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    {% endif %}
      <ul class="nav navbar-nav navbar-right">

            {% if request.user.is_authenticated %}
                <li class="dropdown"><a href="{% url 'users:user_profile' request.user %}"><img style="height:20px; width:20px" class="img-circle" src="{{ request.user.userprofile.profil_photo.url }}"/> {{ request.user.get_full_name }}</a></li>
                <li><a href="{% url 'users:user_edit_profile' %}">Profili Düzenle</a> </li>

                <li><a href="{% url 'users:user_logout' %}">Çıkış</a></li>
                {% else %}
                    <li><a href="{% url 'users:user_login' %}">Giriş</a></li>
            {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            {% block icerik %}

            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

templates/form_template.html
{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            <br>
            {{ field.errors }}
        {% endif %}
        {% if field.help_text %}
            {{ field.help_text|safe }}
        {% endif %}
    </div>
{% endfor %}