djangogirls/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from yonetim.views import index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^yonetim/', include('yonetim.urls', namespace='yonetim')),
    url(r'^$', view=index),
    url(r'^users/', include('users.urls', namespace='users')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


users/urls.py
from django.conf.urls import url
from .views import user_create, user_login, user_logout, user_edit_profile, user_list, user_delete, user_change_password, user_profile, user_upload_photo

urlpatterns = [
    url(r'^user_create/$', view=user_create, name='user_create'),
    url(r'^user_login/$', view=user_login, name='user_login'),
    url(r'^user_logout/$', view=user_logout, name='user_logout'),
    url(r'^user_upload_photo/$', user_upload_photo, name='user_upload_photo'),
    url(r'^user_edit_profile/$', view=user_edit_profile, name='user_edit_profile'),
    url(r'^user_list/$', view=user_list, name='user_list'),
    url(r'^delete/(?P<username>[-\w]+)/$', view=user_delete, name='user_delete'),
    url(r'^password_change/$', view=user_change_password, name='password_change'),
    url(r'^(?P<username>.+)/$', user_profile, name='user_profile')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


def upload_to(instance, filename):
    return '%s/%s/%s' %('profile_photo', instance.user.username, filename)


class UserProfile(models.Model):
    ERKEK = 'E'
    KIZ = 'K'
    OTHER = 'O'
    CINSIYET = ((ERKEK, 'Erkek'),(KIZ, 'Kız'),(OTHER, 'Other'))

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    telefon_numarasi = models.CharField(max_length=11, verbose_name='Telefon Numarası', blank=True, null=True)
    cinsiyet = models.CharField(max_length=1, default=3, verbose_name='Cinsiyet', choices=CINSIYET, blank=True)
    dogum = models.DateField(blank=True, verbose_name='Doğum tarihi', null=True)
    profil_photo = models.ImageField(upload_to=upload_to, verbose_name='Profil Fotoğrafı', default='profile_photo/default.png')

    class Meta:
        verbose_name='Profil'
        verbose_name_plural='Profil'

    def get_full_name_or_username(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return self.user.username

    def __str__(self):
        return '%s Profile'%(self.user.get_full_name_or_username())

def created_user_profile(instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(receiver=created_user_profile, sender=User)
#signal işlemi bir işlemden sonra başka bir işlem yaptırmak istiyorsam kullanılır. Örneğin kullanıcı oluşturduktan sonra profilini oluşturmak gibi.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from bootstrap3_datetime.widgets import DateTimePicker
from .models import UserProfile


class UserCreatForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserCreatForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}

        self.fields['password'].widget=forms.PasswordInput(attrs={'class':'form-control'})

    class Meta:
        model=User
        fields=['first_name', 'last_name', 'username',  'email', 'password']

    def clean_email(self):          #email önceden kullanılmış mı?
        email = self.cleaned_data['email']
        uzunluk = len(User.objects.filter(email=email))
        if uzunluk>0:
            raise forms.ValidationError('Bu email adresi önceden kullanılmış')
        return email


class UserProfileEdit(forms.ModelForm):
    ERKEK = 'E'
    KIZ = 'K'
    OTHER = 'O'
    CINSIYET = ((ERKEK, 'Erkek'), (KIZ, 'Kadın'), (OTHER, 'Other'))

    cinsiyet=forms.CharField(widget=forms.Select(choices=CINSIYET))
    dogum = forms.DateField(input_formats=['%d/%m/%Y'], widget=DateTimePicker(options={'viewMode':'years', "format": "DD/MM/YYYY","pickTime": False}))
    telefon_numarasi=forms.CharField(max_length=11, label='Telefon Numarası', required=False)


    class Meta:
        model = User
        fields=['username', 'first_name', 'last_name', 'email', 'dogum', 'cinsiyet', 'telefon_numarasi']

    def __init__(self, *args, **kwargs):
        super(UserProfileEdit, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}

class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class':'form-control'}

class LoginForm(forms.Form):        #neden form modelform değil
    username=forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def clean_username(self):
        username = self.cleaned_data['username']

        if '@' in username:
            user = User.objects.filter(email=username)
            if len(user) == 1:
                user = user.first()
                return user.username
            else:
                raise forms.ValidationError('Böyle bir kullanıcı bulunamadı!')

        return username


class UserListForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']


class UserUploadPhotoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profil_photo']

users/views.py
from django.shortcuts import render, Http404, HttpResponseRedirect, get_object_or_404, HttpResponse
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash    #kullanıcı şifreyi değiştirdikten sonra oturumda kalmasını sağlıyor.
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
from .forms import UserCreatForm, LoginForm, UserProfileEdit, UserPasswordChangeForm, UserUploadPhotoForm
from yonetim.models import Task


@login_required(login_url='/users/login/')
def user_create(request):
    if not request.user.is_authenticated() or not request.user.is_superuser:
        return HttpResponseRedirect(reverse('yonetim:task_list'))

    form = UserCreatForm(request.POST or None)

    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        yetkiliMi = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

        if yetkiliMi:

            return HttpResponseRedirect(reverse('yonetim:task_list'))

    return render(request, 'users/user_create.html', context={'form':form})


def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('yonetim:task_list'))

    form = LoginForm(request.POST or None)
    if form.is_valid():
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('yonetim:task_list'))
        else:
            hata_mesaji = 'Lütfen kullanıcı adını veya şifrenizi doğru giriniz!'
            return render(request, 'users/user_login.html', context={'form': form, 'hata_mesaji':hata_mesaji})

    return render(request, 'users/user_login.html', context={'form':form})


def user_logout(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('users:user_login'))
    logout(request)
    return HttpResponseRedirect(reverse('users:user_login'))


@login_required(login_url='/users/login/')
def user_edit_profile(request):
    data= {'cinsiyet':request.user.userprofile.cinsiyet, 'dogum':request.user.userprofile.dogum, 'telefon_numarasi':request.user.userprofile.telefon_numarasi}
    user_profile_form=UserProfileEdit(request.POST or None, instance=request.user, initial=data) #instance kısmını yazmasaydık o kişinin bilgileri gelmicekti. initial kısmı da güncelleme yapılacağı için kullanıldı.

    if request.method=="POST":
        if user_profile_form.is_valid():
            user_profile_form.save(commit=True)
            dogum = user_profile_form.cleaned_data['dogum']
            telefon = user_profile_form.cleaned_data['telefon_numarasi']
            cinsiyet = user_profile_form.cleaned_data['cinsiyet']

            request.user.userprofile.cinsiyet= cinsiyet
            request.user.userprofile.telefon_numarasi= telefon
            request.user.userprofile.dogum= dogum
            request.user.userprofile.save()

            messages.success(request,'Kullanıcı bilgileriniz güncellendi!')
            return HttpResponseRedirect(reverse('yonetim:task_list'))

    return render(request, 'users/user_edit_profile.html', context={'form':user_profile_form})


@login_required(login_url='/users/login/')
def user_change_password(request):
    form = UserPasswordChangeForm(request.user, request.POST or None)
    if request.method=='POST':
        if form.is_valid():
            user = form.save(commit=True)
            update_session_auth_hash(request, user)
            messages.success(request, 'Şifreniz başarıyla değiştirildi')
    return render(request, 'users/password_change.html', context={'form': form})


def user_list(request):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('yonetim:task_list'))
    users_list = User.objects.all()
    return render(request, 'users/user_list.html', context={'users_list': users_list})


def user_delete(request, username):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('yonetim:task_list'))
    try:
        user = User.objects.get(username=username)
        user.delete()
        messages.warning(request, "Kullanıcı silindi", extra_tags='danger')

        return HttpResponseRedirect(reverse('users:user_list'))

    except User.DoesNotExist:
        return render(request, 'users/user_list.html')


def user_upload_photo(request):
    if request.method == "POST":
        form = UserUploadPhotoForm(instance=request.user.userprofile, data=request.POST, files=request.FILES)
        if form.is_valid():
            userprofile = form.save(commit=True)
            data = {'is_valid': True, 'image-url':userprofile.profil_photo.url, 'success':'Profil Fotoğrafı Güncellendi'}
            return JsonResponse(data=data)
        else:
            return JsonResponse(data={'is_valid': False})
    else:
        return HttpResponseRedirect(reverse('users:user_edit_profile'))


def user_profile(request,username):
    user = get_object_or_404(User, username=username)
    task_list = Task.objects.filter(worker=user)
    return render(request, 'users/user_profile.html', context={'task_list': task_list, 'user': user})

templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Parola Değiştir {% endblock %}
{% block icerik %}
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <h2 class="page-header">Parola Değiştir</h2>

    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <form action="{% url 'users:password_change' %}" method="post">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <input type="submit" value="Kaydet" class="btn btn-success">
    </form>
        <br><br>
    </div></div></div></div>
{% endblock %}

templates/users/user_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Çalışan Ekle {% endblock %}
{% block icerik %}
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <h2 class="page-header">Çalışan Ekle</h2>

    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <form action="{% url 'users:user_create' %}" method="post">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <input type="submit" value="Kaydet" class="btn btn-success">
    </form>
        <br><br>
    </div></div></div></div>
{% endblock %}

templates/users/user_edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block kodblok %}
        <script src="{% static 'js/upload_js/vendor/jquery.ui.widget.js' %}"></script>
        <script src="{% static 'js/upload_js/jquery.iframe-transport.js' %}"></script>
        <script src="{% static 'js/upload_js/jquery.fileupload.js' %}"></script>
        <script src="{% static 'js/upload_js/basic_upload.js' %}"></script>

{% endblock %}

{% block title %} Profili Düzenle {% endblock %}
{% block icerik %}
    <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Uploading...</h4>
            </div>
            <div class="modal-body">
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <h2 class="page-header">Profili Düzenle</h2>
        <div class="col-lg-5 col-sm-offset-4">
            <img style="border:10px solid navajowhite; height: 200px; width: 200px" class="img-circle" src="{{ request.user.userprofile.profil_photo.url }}"/>
            <br><br>
            <button style="margin-left: 32px" type="button" class="btn btn-primary js-upload-photos">
            <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
            </button>

            {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
            <input id="fileupload" type="file" name="profil_photo"
                style="display: none;"
                data-url="{% url 'users:user_upload_photo' %}"
                data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

        </div>

    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <form action="{% url 'users:user_edit_profile' %}" method="post">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <br>
        {{ form.media }}
        <input type="submit" value="Kaydet" class="btn btn-success">
        <a href="{% url 'users:password_change' %}" class="btn btn-primary">Şifremi Değiştir</a>
    </form>
        <br><br>
    </div></div></div></div>
{% endblock %}

templates/users/user_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Kullanıcılar {% endblock %}
{% block icerik %}
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
    <h2 class="page-header">Kullanıcılar</h2>

    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        {% for user in users_list %}
            <h4 align="left"><a href="{% url 'users:user_profile' user.username %}"> {{ user.username }} </a> | {{ user.first_name }} {{ user.last_name }} <p align="right"> <a class="btn btn-danger" href="{% url 'users:user_delete' user.username %}">Sil</a>
            </p></h4>
            <hr>
        {% endfor %}
        <br><br>
    </div></div></div></div>
{% endblock %}

templates/users/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Giriş Yap {% endblock %}

{% block icerik %}
    <br><br><br>

    <div class="col-lg-4 col-lg-offset-4" style="background-color: #eaeafb; border-style: dashed; border-color: #005500">
    <div class="col-lg-10 col-lg-offset-1">
        <br><br>
        <h2 class="page-header" align="center"> Giriş </h2>
        <form action="{% url 'users:user_login' %}" method="post">
            {% csrf_token %}
            {% include 'form_template.html' %}
            <div class="col-lg-offset-5">
                <input type="submit" class="btn btn-success" value="Giriş">
            </div>
            <br>
            {% if hata_mesaji %}
                <h5 style="color: #761c19">{{ hata_mesaji }}</h5>
            {% endif %}
        </form>
        <br><br>
    </div>
    </div>
{% endblock %}

templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profil {% endblock %}
{% block icerik %}

    <div class="row">
    <div class="col-lg-12">
        <div class="col-lg-3" style="border-radius: 10px; margin-top:20px; background-color: silver; padding-top: 20px; margin-left: 20px; margin-right: 60px;">
            <img style="height: 200px; width: 200px;" src="{{ user.userprofile.profil_photo.url }}" class="img-responsive center-block">
            <hr>
            <h5 style="text-align: center">{{ user.get_full_name|upper }}</h5>
            <p style="text-align: center">{{ user.userprofile.dogum }}</p>
            <p style="text-align: center"><b>Toplam Görev: {{ task_list|length }}</b></p>
            <p style="text-align: center"><a class="btn btn-success" href="{%  url 'users:password_change' %}">Şifre Değiştir</a> <a class="btn btn-primary" href="{% url 'users:user_edit_profile' %}">Profili Düzenle</a> </p>
            <br>
        </div>
        <div class="col-lg-7" style="margin-top: 50px;">
            <div class="col-lg-10">
                <h2 style="text-align: left"> &nbsp;&nbsp;Görevleriniz</h2>
                <hr>
                {% if task_list|length > 0 %}
                {% include 'tasks/my_tasks.html' %}
            {% else %}
                <p style="text-align: center">Göreviniz bulunmamaktadır.</p>
            {% endif %}
            </div>

            <br><br>
    </div></div></div>
{% endblock %}